version: "3"
services:
  requests-db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    container_name: "requests_db"
    environment:
      - POSTGRES_USER=finki_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD:-f1nk1_@dm1n}
      - POSTGRES_DB=finki-services-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - requests_net
  requests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: requests
    depends_on:
      - requests-db
    environment:
      - spring.datasource.url=jdbc:postgresql://requests-db:5432/finki-services-db
      - spring.datasource.password=${DB_PASSWORD:-f1nk1_@dm1n}
      - spring.jpa.show-sql=false
    ports:
      - "8080:8080"
    networks:
      - requests_net
volumes:
  postgres_data:
networks:
  requests_net:
    driver: bridge
